add Slack Support
mvitale1989/docker-taiga pull request #12
Opened 2019-10-02 08:19 UTC by LaysDragon

add Slack plugin support

2019-10-27 12:09 UTC, mvitale1989 requested changes
Looks good, although after some tests i found a few spots that need fixing to make things fully work. After those are done i'd be ready for merging

2019-10-27 12:09 UTC, mvitale1989 commented on Dockerfile
> +  SAML_AUTH_JSON_CONFIG=""\
A default for `SLACK_INTEGRATION_ENABLE` would be good to have here.
```suggestion
  SAML_AUTH_JSON_CONFIG="" \
  SLACK_INTEGRATION_ENABLE="False" \
```

2019-10-27 12:09 UTC, mvitale1989 commented on conf/taiga/docker-settings.py
> +INSTALLED_APPS += ["taiga_contrib_slack"]
This is not truly disabled unless conditionally left out.
```suggestion
if os.getenv("SLACK_INTEGRATION_ENABLE").lower() == "true":
  INSTALLED_APPS += ["taiga_contrib_slack"]
```

2019-10-27 12:09 UTC, mvitale1989 commented on conf/taiga/docker-settings.py
> +  LDAP_START_TLS = os.getenv("LDAP_START_TLS")
Underlying module expects a true boolean for this, so this conversion is needed
```suggestion
  LDAP_START_TLS = True if os.getenv("LDAP_START_TLS").lower() == "true" else False
```

2019-10-27 12:09 UTC, mvitale1989 commented on README.md
> +Other LDAP option can take a look at plugin docs <https://github.com/ensky/taiga-contrib-ldap-auth>
This link references a different ldap plugin than the one that's being used
```suggestion
Other LDAP option can take a look at plugin docs <https://github.com/Monogramm/taiga-contrib-ldap-auth-ext>
```

2019-10-27 12:09 UTC, mvitale1989 commented on README.md
> +- `-e LDAP_BIND_DN=<bind account dn>`
Would add `LDAP_BIND_PASSWORD` here as well, to make it easier to remember for users.
```suggestion
- `-e LDAP_BIND_DN=<bind account dn>`
- `-e LDAP_BIND_PASSWORD=<bind password>`
```

2019-10-29 06:29 UTC, LaysDragon commented on README.md
> +Other LDAP option can take a look at plugin docs <https://github.com/ensky/taiga-contrib-ldap-auth>
oh,you are right ,I pasted the wrong link

2019-10-29 06:34 UTC, LaysDragon commented on conf/taiga/docker-settings.py
> +INSTALLED_APPS += ["taiga_contrib_slack"]
oh yes, I forget to add the condition

2019-10-29 06:40 UTC, LaysDragon commented on Dockerfile
> +  SAML_AUTH_JSON_CONFIG=""\
ok

2019-10-29 06:41 UTC, LaysDragon commented on conf/taiga/docker-settings.py
> +  LDAP_START_TLS = os.getenv("LDAP_START_TLS")
nice detail investigation

2019-10-29 06:41 UTC, LaysDragon commented on README.md
> +- `-e LDAP_BIND_DN=<bind account dn>`
ok that improved the document

2019-10-29 06:49 UTC, LaysDragon commented
OK I have already accept those changes :D

2019-10-30 19:36 UTC, mvitale1989 approved these changes

2019-10-30 19:36 UTC, merged